

% ============================================================================
% Copyright (c) 2025 Thomas Broggini and Liu Xiao. All rights reserved.
%
% This code was jointly written by:
% Thomas Broggini (Frankfurt University, Germany)
% Liu Xiao (Xiangyang First Hospital, China)
%
% The way how the mathematical models and methodologies implemented in this code have been
% individually customized and are not intended for generic use. 
%
% For permission requests or inquiries, please contact:
% Thomas Broggini  : broggini@med.uni-frankfurt.de
% Liu Xiao         : careyneurosurgery@gmail.com  /  carey-lau@foxmail.com
%
% Unauthorized use will be considered a violation of intellectual property rights.
% ============================================================================



% 作者：Thomas Broggini 和 刘晓；法兰克福大学医院；湖北医药学院襄阳市第一人民医院
% By Thomas Broggini (Supervisor) 
% Xiao Liu (Student)
% Department of Neurosurgery
% Neuroscience Centre
% University Hospital Frankfurt
% Goethe University Frankfurt, Germany
% Frankfurt Cancer Institute, Germany

% Xiangyang No.1 people's Hospital, China
% Also an python version coded 
% xiao.liu@stud.uni-frankfurt.de
% 2024.10.09

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function params = getAnalysisParameters()
    
    params = struct();
    
  
    fig = uifigure('Name', 'Pre-set Parameters', 'Position', [100 100 1680 1050]); 
    defaultValues = [0, 0, 30, 80, 0, 8, 115, 2, 20, 1, 1, 0, 30,...
    40, 1, 128, 400, 4, 0.47, 60, 2, 0, 1, 1, 95,1, 1, 1, 1, 1, 3, 4, 1, 16, 1]; 
    
    hei = 1010;
    th = 25;
    sth = 27;
    fontsiz = 17;
    label1 = {' 🔔Change Folder EVERYTIME any change! Adjust dialoge window if you cant see all content'};
    uilabel(fig, 'Text', label1, 'Position', [25 hei 880 th], 'FontWeight', 'bold','FontSize', fontsiz);
    labels = {'*1.Choose data model.......................................................................................................................... ',...
        '*2. Do you want to plot cell traces selected?..............................................................................................................',...
    '     A3: First cell traces number?..........................................................................................................................',...
    '     B4: Last cell traces number?...........................................................................................................................',...
   '*5. Plot the 3D traces selected?..........................................................................................................',...
    '*6. (Critical❗): Minamplitude...................................................................................................................................', ...
    '*7. (Critical❗): Maxwidth..............................................................................................................................................',...
    '*8. (Critical❗): Input the time per frame.......................................................................................................................', ...
    '*9. (Critical❗): peakTolerance_s...............................................................................................................................................',... 
    '*10. (Critical❗): Scale the overlay stuffs................................................................................................................................',...
    '*11. Caculate the connectivity?.........................................................................................................................................',...
    '*12. Do cell limitaition?..........................................................................................................................................',...
    '       A13: First cell number?..........................................................................................................................................',...
    '       B14: Last cell number?.............................................................................................................................................',...
    '*15. Do cells-frames-intensities plot?....................................................................................................................................',...
    '*16. (Critical❗): Cut off distance?..............................................................................................................................',...
    '*17. Distance as control?...................................................................................................................................',...
    '*18. (Critical❗): Decide which traces can be pick up for connectivity caculation.....................................................................................',...
    '*19. (Critical❗): Pre-set threshold of correlation coefficient......................................................................................................',...
    '*20. (Critical❗): Maxspeed of Ca2+ traveling?..........................................................................................'...
    '*21. (Critical❗): Minspeed of Ca2+ traveling?.......................................................................................',...
    '*22. Change corr(Do not change it if necessary)?..........................................................................................................',...
    '*23. Visulaization of the Correlations on Figure?..........................................................................................................',...
    '*24. Lable the cell by number?.................................................................................................................................',...
    '*25. (Critical❗): Threshold for parameter 19"s calculation (lookback):..............................................................................................',...
    '*26. Find the trigger cells?.................................................................................................................................................',...
    '*27. Show the connectivity plot?...............................................................................................................................................',...
    '*28. Show the cut-off information?.........................................................................................................................................',...
    '*29. small-word theory caculation?..........................................................................................................',...
    '*30. Classifying cells based on the number of neighbors?..........................................................................................................',...
    '*31. (Critical❗): Num of cells at least blinking together can be defined as Trigger cells?..........................................................................................................',...
    '*32. (Critical❗): Num of cells at least blinking together can be defined as Hub cells?..........................................................................................................',...
    '*33. Find all cells that have a periodic wave?..........................................................................................................',...
    '*34. (Critical❗): How you define the periodicity related to peak in time?..........................................................................................................',...
    '*35. NetworkX ploting?...................................................................................................................................................................'};
    
    explantation1={'Note! Model 1-3 are controls for cross-correlation analysis; Model 4 tests the method'};
    uilabel(fig, 'Text', explantation1, 'Position', [870 hei 880 th], 'FontWeight', 'bold','FontSize', fontsiz);
    explanations = {'0: empirical data; 1: circular shift; 2: scrambled;3: linear shift; 4: distant cells (>400 um)；',...
    'This function will plot cell traces you want to plot',...
    'First time run, do any number you want. Do not excess the total number of ROIs',...
    'First time run, do any number you want. Do not excess the total number of ROIs',...
    'Do the defauts value please', ...
    'Minimum amplitude of the peaks',...
    'Maximum width of the peaks in seconds',...
    'This is not HZ,it is time in seconds / frame, eg: 0.5hz = 2s/frame',...
    'Represents the temporal spreading width of each Ca²⁺ peak, used for matching coactivity'...
    'According your scale (uM) in one piexl, my frame is 1 uM / piexl, so it is 1',...
    'Caculate the correlation between cells',...
    'Which part of the cells you want to do the visulization?',...
    'First cell number to begin with',...
    'Last cell number to end with',...
    'Do cells-frames-intensities plot',...
    'The max distance (um) you set between the points to be compared for caculating the connectivity',...
    'When you chose mode 4, distant cells that > 400 um will be analysised',...
    'Here we define that one trace has 4 peaks (3 cycles) can be considered as positive cell'...
    'Presetting is 0.49, will be recaulated by para. 25 with 3 other modes',...
    'in um/s (converted to um/frames)',...
    'in um/s (converted to um/frames',...
    'if change_corr = 1, the modified CC.dat file is read in and the correlations are taken over',...
    'Lable the cell by number',...
    'If 0, means there is only lines without marks represnets the cell number',...
    'Threshold to caculate the cutoff value at para.19 (at least 95th percentile of scrambled data)',...
    'Find the cells blinks the most strong',...
    'Plot the connectivity',...
    'Plot the cutoff over distance map',...
    'Caculate the mean shortest path and coefficients to test if the network has small-word structure',...
    '---', ...
    '---   🔔Notes: Adjust the dialoge window if you cant see all content',...
    '-',...
    '-',...
    'When you caculate the periodicity,how many inte-peak shift that can be accepted (in second)',...
    'Schematic network simulate the true network'};
    editFields = cell(1, numel(explanations));
    for i = 1:numel(explanations)
        editFields{i} = uieditfield(fig, 'numeric', 'Value', defaultValues(i), 'Position', [750 hei-(i)*sth+5 90 th], 'FontSize', fontsiz); 
    end 
   for i = 1:numel(explanations)
        uilabel(fig, 'Text', labels{i}, 'Position', [25 hei-(i)*sth 720 th], 'FontWeight', 'bold','FontSize', fontsiz);
        uilabel(fig, 'Text', explanations{i}, 'Position', [870 hei-(i)*sth 850 th], 'FontWeight', 'bold','FontSize', fontsiz);
   end
    
   
   submitButton = uibutton(fig, 'push', 'Text', ...
       'Submit the parameters', 'Position', [545 hei-1000 500 40], ...
       'FontWeight', 'bold','FontSize', 16,'ButtonPushedFcn', @(btn,event) submitCallback());

   
    
    function submitCallback(~, ~)
        answer = zeros(numel(explanations), 1);
        for i = 1:numel(explanations)
            answer(i) = editFields{i}.Value;
        end
        if ~any(isnan(answer))
           
            params.mode = answer(1);
            params.plot_cells_traces = answer(2);
            params.firstCellTrace = answer(3);
            params.lastCellTrace = answer(4);
            params.plot_3d = answer(5);
            params.minamplitude = answer(6);
            params.maxwidth = answer(7);
            params.secondsPerFrame = answer(8);
            params.peakTolerance_s = answer(9);
            params.scaling = answer(10);
            params.cacul_corr = answer(11);
            params.do_celllimit = answer(12);
            params.firstcell = answer(13);
            params.lastcell = answer(14);
            params.do_dotplot = answer(15);
            params.dcutoff = answer(16);
            params.dcutoff_distant_cells = answer(17);
            params.pk_num_define = answer(18);
            params.threshcorr = answer(19);
            params.maxspeed = answer(20);
            params.minspeed = answer(21);
            params.change_corr = answer(22);
            params.do_lines_on_image = answer(23);
            params.numbering = answer(24);
            params.im_percentiles = answer(25);
            params.find_triggercells = answer(26);
            params.plot_connectivity = answer(27);
            params.plot_C_vs_D = answer(28);
            params.do_networktheory = answer(29);
            params.classify_neighbor_of_connections = answer(30);
            params.define_trigger_cells = answer(31);
            params.define_hub_cells = answer(32);
            params.find_periodicities = answer(33);
            params.pk_std = answer(34);
            params.plot_networkx = answer(35);
            
           
            

            for i = 1:numel(explanations)
                disp(['Answer ' num2str(i) ': ' num2str(answer(i))]);
            end
        else
            errordlg('Please enter valid numerical values for all questions.', 'Error');
        end
        
        answer = questdlg('All parameters well set?', 'Confirmation', 'Yes', 'No', 'Yes');
        if strcmp(answer, 'Yes')
            close(fig);
        end
    end


    uiwait(fig);
end

